---
- name: Copy Docker compose folder
  copy:
    src: "{{ inventory_dir }}/compose"
    dest: "{{ ansible_env.HOME }}"

- name: Copy Docker template files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "templates/compose/nginx/config/site.conf.j2", dest: "{{ project_src }}/nginx/config/site.conf" }
    - { src: "templates/compose/docker-compose.yml.j2", dest: "{{ project_src }}/docker-compose.yml" }

- name: Install openssl packages
  apt:
    name: openssl
    update_cache: yes
    state: present

- name: "Check if certificates exist"
  command: ls {{ project_src }}/nginx/certificates/{{ wp_site_url }}*.pem && \
           ls {{ project_src }}/nginx/certificates/{{ wp_site_url }}*.crt && \
           ls {{ project_src }}/nginx/certificates/{{ wp_site_url }}*.key
  register: certificates_result
  ignore_errors: true

- name: Generate self-signed certificates
  script: "{{ inventory_dir }}/self-signed-ssl.sh \
          -c=UA -s=Kiev -l=Kiev -o=Docker -u=Docker -e={{ wp_admin_email }} -n={{ wp_site_url }} -p={{ project_src }}/nginx/certificates/"
  when: '"No such file or directory" in certificates_result.stderr'