---
- name: Copy Docker compose folder
  copy:
    src: "{{ inventory_dir }}/compose"
    dest: "{{ ansible_env.HOME }}"

- name: Copy Docker template files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "templates/compose/nginx/config/site.conf.j2", dest: "{{ project_src }}/nginx/config/site.conf" }
    - { src: "templates/compose/docker-compose.yml.j2", dest: "{{ project_src }}/docker-compose.yml" }

- name: Install openssl packages
  apt:
    name: openssl
    update_cache: yes
    state: present

- name: "Check if certificates exist"
  command: ls {{ project_src }}/nginx/certificates/{{ wp_site_url }}.crt && \
           ls {{ project_src }}/nginx/certificates/{{ wp_site_url }}.key
  register: certificates_result
  ignore_errors: true

- name: Generate RSA Key
  command: openssl genrsa \
    -out "{{ project_src }}/nginx/certificates/{{ wp_site_url }}.key" 2048
  args:
    creates: "{{ project_src }}/nginx/certificates/{{ wp_site_url }}.key"
  register: rsa_key_result
  when: '"No such file or directory" in certificates_result.stderr'

- name: Generate CSR
  command: openssl req \
    -new \
    -subj '/C=UA/ST=Kiev/L=Kiev/O=Docker/CN={{ wp_site_url }}'
    -key "{{ project_src }}/nginx/certificates/{{ wp_site_url }}.key" \
    -out "{{ project_src }}/nginx/certificates/{{ wp_site_url }}.csr"
  args:
    creates: "{{ project_src }}/nginx/certificates/{{ wp_site_url }}.csr"
  register: csr_result
  when: rsa_key_result.changed

- name: Generate Self-signed Certificate
  command: openssl req \
    -x509 \
    -sha256 \
    -days 365 \
    -key "{{ project_src }}/nginx/certificates/{{ wp_site_url }}.key" \
    -in "{{ project_src }}/nginx/certificates/{{ wp_site_url }}.csr" \
    -out "{{ project_src }}/nginx/certificates/{{ wp_site_url }}.crt"
  args:
    creates: "{{ project_src }}/nginx/certificates/{{ wp_site_url }}.crt"
  when: csr_result.changed