---
python_repo: ppa:jonathonf/python-2.7
python_packages: ['python2.7', 'python-pip']
pyyaml_packages: python-yaml

pip_packages: python-pip

docker_apt_key_url: https://download.docker.com/linux/ubuntu/gpg
docker_repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
docker_pre_packages: ['apt-transport-https', 'ca-certificates', 'software-properties-common']
docker_packages: docker-ce